version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./server:/var/www/html/
    environment:
      ENVIRONMENT: docker
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      MYSQL_HOST: db
      MYSQL_DBNAME: Img-annotator

  db:
    # image: mariadb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
