-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 22:58:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Img-annotator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Img-annotator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Img-annotator` DEFAULT CHARACTER SET utf8 ;
USE `Img-annotator` ;

-- -----------------------------------------------------
-- Table `Img-annotator`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Img-annotator`.`Stations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))

  CREATE TABLE `Stations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `Stations` (`id`, `name`) VALUES
(1,	'Magic'),
(3,	'Absolute'),
(4,	'Kiss'),
(5,	'Scala'),
(6,	'Jazz'),
(7,	'Hits'),
(8,	'Pirate FM'),
(9,	'Planet Rock'),
(10,	'Clyde');
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Img-annotator`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Img-annotator`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Img-annotator`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Img-annotator`.`Images` (
  `id` INT AUTO_INCREMENT,
  `url` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `time` DATETIME NULL,
  `Stations_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `last_modified` DATETIME NULL,
  PRIMARY KEY (`id`, `Users_id`),
  INDEX `fk_Images_Stations1_idx` (`Stations_id` ASC) VISIBLE,
  INDEX `fk_Images_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Images_Stations1`
    FOREIGN KEY (`Stations_id`)
    REFERENCES `Img-annotator`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Images_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Img-annotator`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Img-annotator`.`Markers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Img-annotator`.`Markers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `top` VARCHAR(45) NULL,
  `left` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `animation_type` VARCHAR(45) NULL,
  `marker_type` VARCHAR(45) NULL,
  `Images_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Markers_Images_idx` (`Images_id` ASC) VISIBLE,
  INDEX `fk_Markers_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Markers_Images`
    FOREIGN KEY (`Images_id`)
    REFERENCES `Img-annotator`.`Images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Markers_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Img-annotator`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Img-annotator`.`Popups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Img-annotator`.`Popups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Markers_id` INT NOT NULL,
  `content` VARCHAR(8000) NULL,
  `background_color` VARCHAR(45) NULL,
  `border_radius` VARCHAR(45) NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Popups_Markers1_idx` (`Markers_id` ASC) VISIBLE,
  INDEX `fk_Popups_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Popups_Markers1`
    FOREIGN KEY (`Markers_id`)
    REFERENCES `Img-annotator`.`Markers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Popups_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Img-annotator`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `Img-annotator`.`Popup_Contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Img-annotator`.`Popup_Contents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Popups_id` INT NOT NULL,
  `widget_type_id` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Popup_Widgets_Popups1_idx` (`Popups_id` ASC) VISIBLE,
  INDEX `fk_Popup_Contents_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Popup_Widgets_Popups1`
    FOREIGN KEY (`Popups_id`)
    REFERENCES `Img-annotator`.`Popups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Popup_Contents_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Img-annotator`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
