
export enum ActionType {
    SET_TOAST = "SET_TOAST",
    SET_IMAGE = "SET_IMAGE",
    SET_POPUP = "SET_POPUP",
    START_LOADING = "START_LOADING",
    END_LOADING = "END_LOADING",
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
}

